version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - database
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=fhdwfhwd
      - PG_DATABASE=kino
      - PG_HOST=database
      - PG_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fhdwfhwd
      POSTGRES_DB: kino
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
